import smtplib, ssl

# def send_email(message, target="khui3850@gmail.com"):
def send_email(message):
    """Sends message to the target email address"""
    host = "smtp.gmail.com"
    port = 465

    username = "khui3850@gmail.com"

    # App password generated by Google under Account 2-Step Verification Settings
    password = "qcho ooet uqct nzsi"
    target = "khui3850@gmail.com"

    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(host, port, context=context) as server:
        server.login(username, password)
        server.sendmail(username, target, message)

if __name__ == "__main__":
    # send_email(message="HELLO THIS IS A TEST", target="khui3850@gmail.com")
    send_email(message="HELLO THIS IS A TEST")