import smtplib, ssl, os

def send_email(message):
    """Sends message to the target email address"""
    host = "smtp.gmail.com"
    port = 465

    username = os.getenv("EMAIL_ADDRESS")

    # App password generated by Google under Account 2-Step Verification Settings
    password = os.getenv("PASSWORD")
    target = os.getenv("EMAIL_ADDRESS")

    context = ssl.create_default_context()

    with smtplib.SMTP_SSL(host, port, context=context) as server:
        server.login(username, password)
        server.sendmail(username, target, message)

if __name__ == "__main__":
    send_email(message="HELLO THIS IS A TEST")